### ISSUE TITLE
another python improvement

### ISSUE THREAD

**Issue by telendt** [lorca/flat_file_benchmark#5]
My Python (2.7.2 from Macports) performs slightly better when list comprehensions is used (instead of list.append):

```
import sys

with open(sys.argv[1]) as f:
    rows = [tuple(line[:-1].split("\t")) for line in f]
    print ",".join(rows[1])
```

**Comment by lorca** [comment]
hey i've updated the benchmark with this, but see no improvement.  it might be because i've wrapped both in a def main now, since this appears to improve performance as suggested by dalik: "Also, variable lookups in module scope (in CPython) incur a dictionary lookup while variable lookups in a function are converted into a fast index lookup. I wrapped the Python code in a "def main(): ..." then called main() to get a 15% speedup."  Might be list comprehensions do something similar.

**Comment by telendt** [comment]
Ok, thanks for explanation. I'm closing this issue in that case.
